INSERT INTO "public"."exercises" ("id", "name", "category", "equipment", "primary_muscles", "secondary_muscles", "default_rest_seconds", "user_id") VALUES
	(468, 'Versa Climber', 'Cardio', 'Machine', '{}', '{}', NULL, NULL),
	(469, 'Walking', 'Cardio', 'Bodyweight', '{}', '{}', NULL, NULL),
	(470, 'Sprinting', 'Cardio', 'Bodyweight', '{}', '{}', NULL, NULL),
	(471, 'Aerobics', 'Cardio', 'Bodyweight', '{}', '{}', NULL, NULL),
	(472, 'Swimming', 'Cardio', 'Bodyweight', '{}', '{}', NULL, NULL),
	(473, 'Boxing', 'Cardio', 'Bodyweight', '{}', '{}', NULL, NULL),
	(474, 'Step Aerobics', 'Cardio', 'Bodyweight', '{}', '{}', NULL, NULL),
	(475, 'Dance Cardio', 'Cardio', 'Bodyweight', '{}', '{}', NULL, NULL),
	(476, 'Assault Bike', 'Cardio', 'Machine', '{}', '{}', NULL, NULL),
	(477, 'Ski Erg', 'Cardio', 'Machine', '{}', '{}', NULL, NULL),
	(478, 'Hiking', 'Cardio', 'Bodyweight', '{}', '{}', NULL, NULL),
	(479, 'Jumping Jacks', 'Cardio', 'Bodyweight', '{}', '{}', NULL, NULL),
	(480, 'Jump Rope', 'Cardio', 'Bodyweight', '{}', '{}', NULL, NULL),
	(481, 'Cycling', 'Cardio', 'Bodyweight', '{}', '{}', NULL, NULL),
	(482, 'High Knees', 'Cardio', 'Bodyweight', '{}', '{}', NULL, NULL),
	(483, 'Shadow Boxing', 'Cardio', 'Bodyweight', '{}', '{}', NULL, NULL),
	(484, 'Spin Bike', 'Cardio', 'Machine', '{}', '{}', NULL, NULL),
	(485, 'Kickboxing', 'Cardio', 'Bodyweight', '{}', '{}', NULL, NULL),
	(486, 'Rowing Machine', 'Cardio', 'Machine', '{}', '{}', NULL, NULL),
	(487, 'Zumba', 'Cardio', 'Bodyweight', '{}', '{}', NULL, NULL),
	(488, 'Battle Ropes', 'Cardio', 'Other', '{}', '{}', NULL, NULL),
	(489, 'Tabata', 'Cardio', 'Bodyweight', '{}', '{}', NULL, NULL),
	(490, 'Treadmill', 'Cardio', 'Machine', '{}', '{}', NULL, NULL),
	(491, 'Elliptical', 'Cardio', 'Machine', '{}', '{}', NULL, NULL),
	(492, 'Stationary Bike', 'Cardio', 'Machine', '{}', '{}', NULL, NULL),
	(493, 'Trail Running', 'Cardio', 'Bodyweight', '{}', '{}', NULL, NULL),
	(494, 'Burpees', 'Cardio', 'Bodyweight', '{}', '{}', NULL, NULL),
	(495, 'Mountain Climbers', 'Cardio', 'Bodyweight', '{}', '{}', NULL, NULL),
	(496, 'Running', 'Cardio', 'Bodyweight', '{}', '{}', NULL, NULL),
	(497, 'HIIT', 'Cardio', 'Bodyweight', '{}', '{}', NULL, NULL),
	(498, 'Jogging', 'Cardio', 'Bodyweight', '{}', '{}', NULL, NULL),
	(499, 'Circuit Training', 'Cardio', 'Bodyweight', '{}', '{}', NULL, NULL),
	(500, 'Stair Climber', 'Cardio', 'Machine', '{}', '{}', NULL, NULL),
	(501, 'Low to High Cable Fly', 'Push', 'Cable', '{"Upper Chest",Chest,"Front Delts"}', '{Biceps}', 180, NULL),
	(502, 'Cable Wrist Curl', 'Pull', 'Cable', '{Forearms}', '{}', 180, NULL),
	(503, 'Cable Reverse Wrist Curl', 'Pull', 'Bodyweight', '{Forearms}', '{}', 180, NULL),
	(236, 'Plate Loaded Iso-Lateral Row', 'Back', 'Bodyweight', '{Lats,"Upper Back"}', '{Biceps,"Rear Delts",Traps}', 180, NULL),
	(237, 'Barbell Calf Raise', 'Legs', 'Barbell', '{Calves}', '{}', NULL, NULL),
	(238, 'Barbell Curl', 'Pull', 'Barbell', '{Biceps}', '{Forearms}', NULL, NULL),
	(239, 'Barbell Front Raise', 'Push', 'Barbell', '{"Front Delts"}', '{"Lateral Delts"}', NULL, NULL),
	(240, 'Barbell Glute Bridge', 'Legs', 'Barbell', '{Glutes,Hamstrings}', '{Core,Adductors}', NULL, NULL),
	(241, 'Barbell Hack Squat', 'Legs', 'Barbell', '{Quads,Glutes}', '{Adductors,Hamstrings}', NULL, NULL),
	(242, 'Barbell Lunge', 'Legs', 'Barbell', '{Quads,Glutes}', '{Hamstrings,Adductors,Core}', NULL, NULL),
	(243, 'Barbell Power Shrug', 'Legs', 'Barbell', '{Traps}', '{Glutes,Quads,Calves}', NULL, NULL),
	(244, 'Barbell Pullover', 'Push', 'Barbell', '{Lats,Chest}', '{Triceps}', NULL, NULL),
	(245, 'Barbell Reverse Lunge', 'Legs', 'Barbell', '{Glutes,Quads}', '{Hamstrings,Adductors}', NULL, NULL),
	(246, 'Barbell Shrug', 'Pull', 'Barbell', '{Traps}', '{Forearms,"Upper Back"}', NULL, NULL),
	(247, 'Behind The Back Barbell Shrug', 'Pull', 'Barbell', '{Traps}', '{Forearms,"Upper Back"}', NULL, NULL),
	(248, 'Behind The Back Deadlift', 'Legs', 'Barbell', '{Glutes,Hamstrings,"Lower Back"}', '{Quads,Traps,Forearms}', NULL, NULL),
	(249, 'Behind The Neck Press', 'Core', 'Barbell', '{"Front Delts",Triceps,"Lateral Delts"}', '{"Upper Back",Core}', NULL, NULL),
	(250, 'Bench Pin Press', 'Push', 'Barbell', '{Chest,Triceps,"Front Delts"}', '{"Upper Back",Lats}', NULL, NULL),
	(251, 'Bench Press', 'Push', 'Barbell', '{Chest,Triceps,"Front Delts"}', '{"Upper Back",Lats}', NULL, NULL),
	(252, 'Bench Pull', 'Pull', 'Barbell', '{"Upper Back",Lats,Rhomboids}', '{"Rear Delts",Biceps,Forearms}', NULL, NULL),
	(253, 'Bent Arm Barbell Pullover', 'Push', 'Barbell', '{Chest,Lats}', '{Triceps,"Upper Chest"}', NULL, NULL),
	(254, 'Bent Over Row', 'Pull', 'Barbell', '{"Upper Back",Lats,Rhomboids}', '{"Rear Delts",Biceps,Forearms}', NULL, NULL),
	(255, 'Box Squat', 'Legs', 'Barbell', '{Glutes,Quads}', '{Hamstrings,Adductors,Core}', NULL, NULL),
	(256, 'Bulgarian Split Squat', 'Legs', 'Barbell', '{Quads,Glutes}', '{Adductors,Hamstrings,Core}', NULL, NULL),
	(257, 'Cheat Curl', 'Pull', 'Barbell', '{Biceps,Forearms}', '{"Upper Back"}', NULL, NULL),
	(258, 'Chest Press', 'Push', 'Machine', '{Chest,Triceps,"Front Delts"}', '{"Upper Chest"}', NULL, NULL),
	(259, 'Chin Ups', 'Pull', 'Bodyweight', '{Lats,Biceps}', '{"Upper Back",Forearms,Rhomboids}', NULL, NULL),
	(260, 'Clean', 'Legs', 'Barbell', '{Quads,Glutes,Traps}', '{Hamstrings,"Upper Back",Calves}', NULL, NULL),
	(261, 'Clean and Jerk', 'Legs', 'Barbell', '{Quads,Glutes,"Front Delts",Triceps}', '{Traps,Core,"Upper Back"}', NULL, NULL),
	(262, 'Clean and Press', 'Legs', 'Barbell', '{Quads,Glutes,"Front Delts",Triceps}', '{Traps,Core,"Upper Back"}', NULL, NULL),
	(263, 'Clean High Pull', 'Legs', 'Barbell', '{Traps,Glutes,Quads}', '{Hamstrings,"Upper Back",Calves}', NULL, NULL),
	(264, 'Clean Pull', 'Legs', 'Barbell', '{Glutes,Hamstrings,Traps}', '{Quads,"Upper Back",Calves}', NULL, NULL),
	(265, 'Close Grip Bench Press', 'Push', 'Barbell', '{Triceps,Chest}', '{"Front Delts","Upper Chest"}', NULL, NULL),
	(266, 'Close Grip Incline Bench Press', 'Push', 'Barbell', '{"Upper Chest",Triceps}', '{Chest,"Front Delts"}', NULL, NULL),
	(267, 'Deadlift', 'Legs', 'Barbell', '{Glutes,Hamstrings,"Lower Back"}', '{Quads,Traps,"Upper Back",Forearms}', NULL, NULL),
	(268, 'Decline Bench Press', 'Push', 'Barbell', '{"Lower Chest",Chest,Triceps}', '{"Front Delts"}', NULL, NULL),
	(269, 'Deficit Deadlift', 'Legs', 'Barbell', '{Glutes,Hamstrings,"Lower Back"}', '{Quads,Traps,"Upper Back",Forearms}', NULL, NULL),
	(270, 'Dips', 'Push', 'Bodyweight', '{"Lower Chest",Triceps}', '{Chest,"Front Delts"}', NULL, NULL),
	(271, 'Dumbbell Bench Press', 'Push', 'Dumbbell', '{Chest,Triceps,"Front Delts"}', '{"Upper Back",Lats}', NULL, NULL),
	(272, 'Dumbbell Bulgarian Split Squat', 'Legs', 'Dumbbell', '{Quads,Glutes}', '{Adductors,Hamstrings,Core}', NULL, NULL),
	(273, 'Dumbbell Curl', 'Pull', 'Dumbbell', '{Biceps}', '{Forearms}', NULL, NULL),
	(274, 'Dumbbell Fly', 'Push', 'Dumbbell', '{Chest}', '{"Front Delts"}', NULL, NULL),
	(275, 'Dumbbell Lateral Raise', 'Push', 'Dumbbell', '{"Lateral Delts"}', '{Traps}', NULL, NULL),
	(276, 'Dumbbell Row', 'Pull', 'Dumbbell', '{"Upper Back",Lats,Rhomboids}', '{"Rear Delts",Biceps,Forearms}', NULL, NULL),
	(277, 'Dumbbell Shoulder Press', 'Push', 'Dumbbell', '{"Front Delts",Triceps,"Lateral Delts"}', '{"Upper Chest"}', NULL, NULL),
	(278, 'Dumbbell Shrug', 'Pull', 'Dumbbell', '{Traps}', '{Forearms,"Upper Back"}', NULL, NULL),
	(279, 'EZ Bar Curl', 'Pull', 'EZ Bar', '{Biceps}', '{Forearms}', NULL, NULL),
	(280, 'Floor Press', 'Push', 'Barbell', '{Chest,Triceps,"Front Delts"}', '{"Upper Back",Lats}', NULL, NULL),
	(281, 'Front Squat', 'Legs', 'Barbell', '{Quads,Glutes}', '{Core,"Upper Back",Adductors}', NULL, NULL),
	(282, 'Goblet Squat', 'Legs', 'Dumbbell', '{Quads,Glutes}', '{Core,Adductors}', NULL, NULL),
	(283, 'Good Morning', 'Legs', 'Barbell', '{Hamstrings,Glutes,"Lower Back"}', '{Core}', NULL, NULL),
	(284, 'Hack Squat', 'Legs', 'Machine', '{Quads,Glutes}', '{Adductors,Hamstrings}', NULL, NULL),
	(285, 'Half Squat', 'Legs', 'Barbell', '{Quads,Glutes}', '{Adductors,Core}', NULL, NULL),
	(286, 'Hammer Curl', 'Pull', 'Dumbbell', '{Biceps,Forearms}', '{}', NULL, NULL),
	(287, 'Hang Clean', 'Legs', 'Barbell', '{Quads,Glutes,Traps}', '{Hamstrings,"Upper Back",Calves}', NULL, NULL),
	(288, 'Hang Power Clean', 'Legs', 'Barbell', '{Quads,Glutes,Traps}', '{Hamstrings,"Upper Back",Calves}', NULL, NULL),
	(289, 'Hang Snatch', 'Legs', 'Barbell', '{Glutes,Traps,"Front Delts"}', '{Quads,"Upper Back",Core}', NULL, NULL),
	(290, 'Hex Bar Deadlift', 'Legs', 'Barbell', '{Quads,Glutes,Hamstrings}', '{"Lower Back",Traps,Forearms}', NULL, NULL),
	(291, 'Hex Bar Shrug', 'Pull', 'Barbell', '{Traps}', '{Forearms,"Upper Back"}', NULL, NULL),
	(292, 'Hip Adduction', 'Legs', 'Machine', '{Adductors}', '{Glutes}', NULL, NULL),
	(293, 'Hip Thrust', 'Legs', 'Barbell', '{Glutes,Hamstrings}', '{Core,Adductors}', NULL, NULL),
	(294, 'Horizontal Leg Press', 'Legs', 'Machine', '{Quads,Glutes}', '{Adductors,Hamstrings}', NULL, NULL),
	(295, 'Incline Bench Press', 'Push', 'Barbell', '{"Upper Chest",Chest,"Front Delts"}', '{Triceps}', NULL, NULL),
	(296, 'Incline Dumbbell Bench Press', 'Push', 'Dumbbell', '{"Upper Chest",Chest,"Front Delts"}', '{Triceps}', NULL, NULL),
	(297, 'Jefferson Deadlift', 'Legs', 'Barbell', '{Quads,Glutes,Hamstrings}', '{"Lower Back",Adductors,Forearms}', NULL, NULL),
	(298, 'Jefferson Squat', 'Legs', 'Barbell', '{Quads,Glutes}', '{Adductors,Core,Hamstrings}', NULL, NULL),
	(299, 'JM Press', 'Push', 'Barbell', '{Triceps}', '{Chest,"Front Delts"}', NULL, NULL),
	(300, 'Landmine Press', 'Push', 'Barbell', '{"Front Delts","Upper Chest",Triceps}', '{Core,"Lateral Delts"}', NULL, NULL),
	(301, 'Landmine Squat', 'Legs', 'Barbell', '{Quads,Glutes}', '{Core,Adductors}', NULL, NULL),
	(302, 'Lat Pulldown', 'Pull', 'Cable', '{Lats,"Upper Back"}', '{Biceps,Forearms,Rhomboids}', NULL, NULL),
	(303, 'Leg Extension', 'Legs', 'Machine', '{Quads}', '{"Hip Flexors"}', NULL, NULL),
	(304, 'Log Press', 'Push', 'Barbell', '{"Front Delts",Triceps,"Upper Chest"}', '{Core,"Lateral Delts"}', NULL, NULL),
	(305, 'Lying Leg Curl', 'Legs', 'Machine', '{Hamstrings}', '{Calves}', NULL, NULL),
	(306, 'Lying Tricep Extension', 'Push', 'Barbell', '{Triceps}', '{"Front Delts"}', NULL, NULL),
	(307, 'Machine Calf Raise', 'Legs', 'Machine', '{Calves}', '{}', NULL, NULL),
	(308, 'Machine Chest Fly', 'Push', 'Machine', '{Chest}', '{"Front Delts"}', NULL, NULL),
	(309, 'Machine Shoulder Press', 'Push', 'Machine', '{"Front Delts",Triceps,"Lateral Delts"}', '{"Upper Chest"}', NULL, NULL),
	(310, 'Meadows Row', 'Pull', 'Barbell', '{Lats,"Upper Back",Rhomboids}', '{Biceps,"Rear Delts",Forearms}', NULL, NULL),
	(311, 'Military Press', 'Push', 'Barbell', '{"Front Delts",Triceps}', '{"Lateral Delts","Upper Chest",Core}', NULL, NULL),
	(312, 'Muscle Snatch', 'Pull', 'Barbell', '{"Front Delts",Traps,"Upper Back"}', '{Glutes,Core}', NULL, NULL),
	(313, 'Muscle Ups', 'Push', 'Bodyweight', '{Lats,Chest,Triceps}', '{"Upper Back",Biceps,"Front Delts",Core}', NULL, NULL),
	(314, 'Neck Curl', 'Core', 'Machine', '{Neck}', '{}', NULL, NULL),
	(315, 'Neck Extension', 'Core', 'Machine', '{Neck}', '{}', NULL, NULL),
	(316, 'One Arm Landmine Press', 'Push', 'Barbell', '{"Front Delts","Upper Chest",Triceps}', '{Core,"Lateral Delts"}', NULL, NULL),
	(317, 'Overhead Squat', 'Legs', 'Barbell', '{Quads,Glutes,"Front Delts","Upper Back"}', '{Core,Hamstrings}', NULL, NULL),
	(318, 'Pause Deadlift', 'Legs', 'Barbell', '{Glutes,Hamstrings,"Lower Back"}', '{Quads,Traps,"Upper Back",Forearms}', NULL, NULL),
	(319, 'Pause Squat', 'Legs', 'Barbell', '{Quads,Glutes}', '{Adductors,Core,Hamstrings}', NULL, NULL),
	(320, 'Paused Bench Press', 'Push', 'Barbell', '{Chest,Triceps,"Front Delts"}', '{"Upper Back",Lats}', NULL, NULL),
	(321, 'Pendlay Row', 'Pull', 'Barbell', '{"Upper Back",Lats,Rhomboids}', '{"Rear Delts",Biceps,Forearms}', NULL, NULL),
	(322, 'Pin Squat', 'Legs', 'Barbell', '{Quads,Glutes}', '{Adductors,Core,Hamstrings}', NULL, NULL),
	(323, 'Power Clean', 'Legs', 'Barbell', '{Quads,Glutes,Traps}', '{Hamstrings,"Upper Back",Calves}', NULL, NULL),
	(324, 'Power Snatch', 'Legs', 'Barbell', '{Glutes,Traps,"Front Delts"}', '{Quads,"Upper Back",Core}', NULL, NULL),
	(325, 'Preacher Curl', 'Pull', 'Barbell', '{Biceps}', '{Forearms}', NULL, NULL),
	(326, 'Pull Ups', 'Pull', 'Bodyweight', '{Lats,"Upper Back"}', '{Biceps,Forearms,Rhomboids}', NULL, NULL),
	(327, 'Push Jerk', 'Legs', 'Barbell', '{"Front Delts",Triceps,Quads,Glutes}', '{Core,"Upper Back"}', NULL, NULL),
	(328, 'Push Press', 'Legs', 'Barbell', '{"Front Delts",Triceps,Quads,Glutes}', '{Core,"Upper Back"}', NULL, NULL),
	(329, 'Push Ups', 'Push', 'Bodyweight', '{Chest,Triceps,"Front Delts"}', '{Core}', NULL, NULL),
	(330, 'Rack Pull', 'Legs', 'Barbell', '{Glutes,Hamstrings,"Lower Back"}', '{Traps,"Upper Back",Forearms}', NULL, NULL),
	(331, 'Reverse Barbell Curl', 'Pull', 'Barbell', '{Forearms,Biceps}', '{}', NULL, NULL),
	(332, 'Reverse Grip Bench Press', 'Push', 'Barbell', '{"Upper Chest",Triceps}', '{Chest,"Front Delts"}', NULL, NULL),
	(333, 'Reverse Wrist Curl', 'Pull', 'Barbell', '{Forearms}', '{}', NULL, NULL),
	(334, 'Romanian Deadlift', 'Legs', 'Barbell', '{Hamstrings,Glutes}', '{"Lower Back",Adductors}', NULL, NULL),
	(335, 'Safety Bar Squat', 'Legs', 'Barbell', '{Quads,Glutes}', '{"Upper Back",Core,Adductors}', NULL, NULL),
	(336, 'Seated Cable Row', 'Pull', 'Cable', '{"Upper Back",Lats,Rhomboids}', '{"Rear Delts",Biceps,Forearms}', NULL, NULL),
	(337, 'Seated Dumbbell Shoulder Press', 'Push', 'Dumbbell', '{"Front Delts",Triceps,"Lateral Delts"}', '{"Upper Chest"}', NULL, NULL),
	(338, 'Seated Leg Curl', 'Legs', 'Machine', '{Hamstrings}', '{Calves}', NULL, NULL),
	(339, 'Seated Shoulder Press', 'Push', 'Barbell', '{"Front Delts",Triceps}', '{"Lateral Delts","Upper Chest",Core}', NULL, NULL),
	(340, 'Shoulder Pin Press', 'Push', 'Barbell', '{"Front Delts",Triceps}', '{"Lateral Delts","Upper Chest",Core}', NULL, NULL),
	(341, 'Shoulder Press', 'Push', 'Barbell', '{"Front Delts",Triceps}', '{"Lateral Delts","Upper Chest",Core}', NULL, NULL),
	(342, 'Single Leg Deadlift', 'Legs', 'Barbell', '{Glutes,Hamstrings}', '{Core,"Lower Back",Abductors}', NULL, NULL),
	(343, 'Single Leg Romanian Deadlift', 'Legs', 'Barbell', '{Glutes,Hamstrings}', '{Core,"Lower Back",Abductors}', NULL, NULL),
	(344, 'Sled Leg Press', 'Legs', 'Machine', '{Quads,Glutes}', '{Adductors,Hamstrings}', NULL, NULL),
	(345, 'Smith Machine Bench Press', 'Push', 'Machine', '{Chest,Triceps,"Front Delts"}', '{"Upper Back",Lats}', NULL, NULL),
	(346, 'Smith Machine Shrug', 'Pull', 'Machine', '{Traps}', '{Forearms,"Upper Back"}', NULL, NULL),
	(347, 'Smith Machine Squat', 'Legs', 'Machine', '{Quads,Glutes}', '{Adductors,Core,Hamstrings}', NULL, NULL),
	(348, 'Snatch', 'Legs', 'Barbell', '{Glutes,Traps,"Front Delts"}', '{Quads,"Upper Back",Core}', NULL, NULL),
	(349, 'Snatch Deadlift', 'Legs', 'Barbell', '{Glutes,Hamstrings,"Lower Back"}', '{Quads,Traps,"Upper Back",Forearms}', NULL, NULL),
	(350, 'Snatch Pull', 'Legs', 'Barbell', '{Glutes,Hamstrings,Traps}', '{Quads,"Upper Back",Calves}', NULL, NULL),
	(351, 'Spider Curl', 'Pull', 'Barbell', '{Biceps}', '{Forearms}', NULL, NULL),
	(352, 'Split Jerk', 'Legs', 'Barbell', '{"Front Delts",Triceps,Quads,Glutes}', '{Core,"Upper Back"}', NULL, NULL),
	(353, 'Split Squat', 'Legs', 'Barbell', '{Quads,Glutes}', '{Adductors,Hamstrings,Core}', NULL, NULL),
	(354, 'Spoto Press', 'Push', 'Barbell', '{Chest,Triceps,"Front Delts"}', '{"Upper Back",Lats}', NULL, NULL),
	(355, 'Squat', 'Legs', 'Barbell', '{Quads,Glutes}', '{Adductors,Core,Hamstrings}', NULL, NULL),
	(356, 'Stiff Leg Deadlift', 'Legs', 'Barbell', '{Hamstrings,Glutes,"Lower Back"}', '{Adductors}', NULL, NULL),
	(357, 'Strict Curl', 'Pull', 'Barbell', '{Biceps}', '{Forearms}', NULL, NULL),
	(358, 'Sumo Deadlift', 'Legs', 'Barbell', '{Glutes,Hamstrings,Adductors}', '{Quads,"Lower Back",Traps,Forearms}', NULL, NULL),
	(359, 'Sumo Squat', 'Legs', 'Barbell', '{Quads,Glutes,Adductors}', '{Hamstrings,Core}', NULL, NULL),
	(360, 'T Bar Row', 'Pull', 'Barbell', '{"Upper Back",Lats,Rhomboids}', '{"Rear Delts",Biceps,Forearms}', NULL, NULL),
	(361, 'Thruster', 'Push', 'Barbell', '{Quads,Glutes,"Front Delts",Triceps}', '{Core,"Upper Chest"}', NULL, NULL),
	(362, 'Tricep Extension', 'Push', 'Barbell', '{Triceps}', '{"Front Delts"}', NULL, NULL),
	(363, 'Tricep Pushdown', 'Push', 'Cable', '{Triceps}', '{Forearms}', NULL, NULL),
	(364, 'Upright Row', 'Pull', 'Barbell', '{"Lateral Delts",Traps}', '{"Front Delts","Upper Back"}', NULL, NULL),
	(365, 'Viking Press', 'Push', 'Barbell', '{"Front Delts",Triceps,"Upper Chest"}', '{Core,"Lateral Delts"}', NULL, NULL),
	(366, 'Walking Lunge', 'Legs', 'Barbell', '{Quads,Glutes}', '{Hamstrings,Adductors,Core}', NULL, NULL),
	(367, 'Wall Ball', 'Legs', 'Dumbbell', '{Quads,Glutes,"Front Delts"}', '{Core,Triceps}', NULL, NULL),
	(368, 'Wide Grip Bench Press', 'Push', 'Barbell', '{Chest,Triceps,"Front Delts"}', '{"Upper Back",Lats}', NULL, NULL),
	(369, 'Wrist Curl', 'Pull', 'Barbell', '{Forearms}', '{}', NULL, NULL),
	(370, 'Yates Row', 'Pull', 'Barbell', '{Lats,"Upper Back",Rhomboids}', '{Biceps,"Rear Delts",Forearms}', NULL, NULL),
	(371, 'Z Press', 'Push', 'Barbell', '{"Front Delts",Triceps,Core}', '{"Upper Back","Lateral Delts"}', NULL, NULL),
	(372, 'Zercher Deadlift', 'Legs', 'Barbell', '{Quads,Glutes,Hamstrings}', '{"Lower Back",Traps,Forearms,Core}', NULL, NULL),
	(373, 'Zercher Squat', 'Legs', 'Barbell', '{Quads,Glutes}', '{Core,"Upper Back",Adductors}', NULL, NULL),
	(374, 'Cable Bicep Curl', 'Pull', 'Cable', '{Biceps}', '{Forearms}', NULL, NULL),
	(375, 'Cable Crunch', 'Core', 'Cable', '{Core}', '{"Hip Flexors"}', NULL, NULL),
	(376, 'Cable External Rotation', 'Pull', 'Cable', '{"Rear Delts"}', '{"Upper Back"}', NULL, NULL),
	(377, 'Cable Fly', 'Push', 'Cable', '{Chest}', '{"Front Delts"}', NULL, NULL),
	(378, 'Cable Hammer Curl', 'Pull', 'Cable', '{Biceps,Forearms}', '{}', NULL, NULL),
	(379, 'Cable Kickback', 'Push', 'Cable', '{Triceps}', '{"Rear Delts"}', NULL, NULL),
	(380, 'Cable Lateral Raise', 'Push', 'Cable', '{"Lateral Delts"}', '{Traps}', NULL, NULL),
	(381, 'Cable Leg Extension', 'Legs', 'Cable', '{Quads}', '{"Hip Flexors"}', NULL, NULL),
	(382, 'Cable Overhead Tricep Extension', 'Push', 'Cable', '{Triceps}', '{"Front Delts"}', NULL, NULL),
	(383, 'Cable Pull Through', 'Legs', 'Cable', '{Glutes,Hamstrings}', '{"Lower Back",Adductors}', NULL, NULL),
	(384, 'Cable Reverse Fly', 'Pull', 'Cable', '{"Rear Delts",Rhomboids}', '{"Upper Back",Traps}', NULL, NULL),
	(385, 'Cable Shrug', 'Pull', 'Cable', '{Traps}', '{Forearms,"Upper Back"}', NULL, NULL),
	(386, 'Cable Upright Row', 'Pull', 'Cable', '{"Lateral Delts",Traps}', '{"Front Delts","Upper Back"}', NULL, NULL),
	(387, 'Cable Woodchopper', 'Core', 'Cable', '{Obliques,Core}', '{"Hip Flexors"}', NULL, NULL),
	(388, 'Close Grip Lat Pulldown', 'Pull', 'Cable', '{Lats,"Upper Back"}', '{Biceps,Forearms,Rhomboids}', NULL, NULL),
	(389, 'Face Pull', 'Pull', 'Cable', '{"Rear Delts","Upper Back",Rhomboids}', '{Traps}', NULL, NULL),
	(390, 'High Pulley Crunch', 'Core', 'Cable', '{Core}', '{"Hip Flexors"}', NULL, NULL),
	(391, 'Incline Cable Curl', 'Pull', 'Cable', '{Biceps}', '{Forearms}', NULL, NULL),
	(392, 'Lying Cable Curl', 'Legs', 'Cable', '{Hamstrings}', '{Calves}', NULL, NULL),
	(393, 'One Arm Cable Bicep Curl', 'Pull', 'Cable', '{Biceps}', '{Forearms}', NULL, NULL),
	(394, 'One Arm Lat Pulldown', 'Pull', 'Cable', '{Lats,"Upper Back"}', '{Biceps,Forearms,Rhomboids}', NULL, NULL),
	(395, 'One Arm Pulldown', 'Pull', 'Cable', '{Lats}', '{"Upper Back",Triceps}', NULL, NULL),
	(396, 'One Arm Seated Cable Row', 'Pull', 'Cable', '{"Upper Back",Lats,Rhomboids}', '{"Rear Delts",Biceps,Forearms}', NULL, NULL),
	(397, 'Overhead Cable Curl', 'Pull', 'Cable', '{Biceps}', '{Forearms}', NULL, NULL),
	(398, 'Reverse Grip Lat Pulldown', 'Pull', 'Cable', '{Lats,Biceps}', '{"Upper Back",Forearms,Rhomboids}', NULL, NULL),
	(399, 'Reverse Grip Tricep Pushdown', 'Push', 'Cable', '{Triceps}', '{Forearms}', NULL, NULL),
	(400, 'Standing Cable Crunch', 'Core', 'Cable', '{Core}', '{"Hip Flexors"}', NULL, NULL),
	(401, 'Straight Arm Pulldown', 'Pull', 'Cable', '{Lats}', '{"Upper Back",Triceps}', NULL, NULL),
	(402, 'Tricep Rope Pushdown', 'Push', 'Cable', '{Triceps}', '{Forearms}', NULL, NULL),
	(403, 'Arnold Press', 'Push', 'Dumbbell', '{"Front Delts","Lateral Delts",Triceps}', '{"Upper Chest"}', NULL, NULL),
	(404, 'Bent Over Dumbbell Row', 'Pull', 'Dumbbell', '{"Upper Back",Lats,Rhomboids}', '{"Rear Delts",Biceps,Forearms}', NULL, NULL),
	(405, 'Chest Supported Dumbbell Row', 'Pull', 'Dumbbell', '{"Upper Back",Lats,Rhomboids}', '{"Rear Delts",Biceps,Forearms}', NULL, NULL),
	(406, 'Close Grip Dumbbell Bench Press', 'Push', 'Dumbbell', '{Triceps,Chest}', '{"Front Delts","Upper Chest"}', NULL, NULL),
	(407, 'Decline Dumbbell Bench Press', 'Push', 'Dumbbell', '{"Lower Chest",Chest,Triceps}', '{"Front Delts"}', NULL, NULL),
	(408, 'Decline Dumbbell Fly', 'Push', 'Dumbbell', '{"Lower Chest",Chest}', '{"Front Delts"}', NULL, NULL),
	(409, 'Dumbbell Bench Pull', 'Pull', 'Dumbbell', '{"Upper Back",Lats,Rhomboids}', '{"Rear Delts",Biceps,Forearms}', NULL, NULL),
	(410, 'Dumbbell Calf Raise', 'Legs', 'Dumbbell', '{Calves}', '{}', NULL, NULL),
	(411, 'Dumbbell Clean and Press', 'Legs', 'Dumbbell', '{Quads,Glutes,"Front Delts",Triceps}', '{Traps,Core,"Upper Back"}', NULL, NULL),
	(412, 'Dumbbell Concentration Curl', 'Pull', 'Dumbbell', '{Biceps}', '{Forearms}', NULL, NULL),
	(413, 'Dumbbell Deadlift', 'Legs', 'Dumbbell', '{Glutes,Hamstrings,"Lower Back"}', '{Quads,Traps,"Upper Back",Forearms}', NULL, NULL),
	(414, 'Dumbbell External Rotation', 'Pull', 'Dumbbell', '{"Rear Delts"}', '{"Upper Back"}', NULL, NULL),
	(415, 'Dumbbell Face Pull', 'Pull', 'Dumbbell', '{"Rear Delts","Upper Back",Rhomboids}', '{Traps}', NULL, NULL),
	(416, 'Dumbbell Floor Press', 'Push', 'Dumbbell', '{Chest,Triceps,"Front Delts"}', '{"Upper Back",Lats}', NULL, NULL),
	(417, 'Dumbbell Front Raise', 'Push', 'Dumbbell', '{"Front Delts"}', '{"Lateral Delts"}', NULL, NULL),
	(418, 'Dumbbell Front Squat', 'Legs', 'Dumbbell', '{Quads,Glutes}', '{Core,"Upper Back",Adductors}', NULL, NULL),
	(419, 'Dumbbell Hang Clean', 'Legs', 'Dumbbell', '{Quads,Glutes,Traps}', '{Hamstrings,"Upper Back",Calves}', NULL, NULL),
	(420, 'Dumbbell High Pull', 'Legs', 'Dumbbell', '{Traps,Glutes,Quads}', '{Hamstrings,"Upper Back",Calves}', NULL, NULL),
	(421, 'Dumbbell Incline Y Raise', 'Pull', 'Dumbbell', '{"Rear Delts","Upper Back"}', '{Traps,Rhomboids}', NULL, NULL),
	(422, 'Dumbbell Lunge', 'Legs', 'Dumbbell', '{Quads,Glutes}', '{Hamstrings,Adductors,Core}', NULL, NULL),
	(423, 'Dumbbell Pullover', 'Push', 'Dumbbell', '{Lats,Chest}', '{Triceps}', NULL, NULL),
	(424, 'Dumbbell Push Press', 'Legs', 'Dumbbell', '{"Front Delts",Triceps,Quads,Glutes}', '{Core,"Upper Back"}', NULL, NULL),
	(425, 'Dumbbell Reverse Curl', 'Pull', 'Dumbbell', '{Forearms,Biceps}', '{}', NULL, NULL),
	(426, 'Dumbbell Reverse Fly', 'Pull', 'Dumbbell', '{"Rear Delts",Rhomboids}', '{"Upper Back",Traps}', NULL, NULL),
	(427, 'Dumbbell Reverse Wrist Curl', 'Pull', 'Dumbbell', '{Forearms}', '{}', NULL, NULL),
	(428, 'Dumbbell Romanian Deadlift', 'Legs', 'Dumbbell', '{Hamstrings,Glutes}', '{"Lower Back",Adductors}', NULL, NULL),
	(429, 'Dumbbell Side Bend', 'Core', 'Dumbbell', '{Obliques}', '{Core}', NULL, NULL),
	(430, 'Dumbbell Snatch', 'Legs', 'Dumbbell', '{Glutes,Traps,"Front Delts"}', '{Quads,"Upper Back",Core}', NULL, NULL),
	(431, 'Dumbbell Split Squat', 'Legs', 'Dumbbell', '{Quads,Glutes}', '{Adductors,Hamstrings,Core}', NULL, NULL),
	(432, 'Dumbbell Squat', 'Legs', 'Dumbbell', '{Quads,Glutes}', '{Adductors,Core,Hamstrings}', NULL, NULL),
	(433, 'Dumbbell Thruster', 'Push', 'Dumbbell', '{Quads,Glutes,"Front Delts",Triceps}', '{Core,"Upper Chest"}', NULL, NULL),
	(434, 'Dumbbell Tricep Extension', 'Push', 'Dumbbell', '{Triceps}', '{"Front Delts"}', NULL, NULL),
	(435, 'Dumbbell Tricep Kickback', 'Push', 'Dumbbell', '{Triceps}', '{"Rear Delts"}', NULL, NULL),
	(436, 'Dumbbell Upright Row', 'Pull', 'Dumbbell', '{"Lateral Delts",Traps}', '{"Front Delts","Upper Back"}', NULL, NULL),
	(437, 'Dumbbell Walking Calf Raise', 'Legs', 'Dumbbell', '{Calves}', '{}', NULL, NULL),
	(438, 'Dumbbell Wrist Curl', 'Pull', 'Dumbbell', '{Forearms}', '{}', NULL, NULL),
	(439, 'Dumbbell Z Press', 'Push', 'Dumbbell', '{"Front Delts",Triceps,Core}', '{"Upper Back","Lateral Delts"}', NULL, NULL),
	(440, 'Incline Dumbbell Curl', 'Pull', 'Dumbbell', '{Biceps}', '{Forearms}', NULL, NULL),
	(441, 'Incline Dumbbell Fly', 'Push', 'Dumbbell', '{"Upper Chest",Chest}', '{"Front Delts"}', NULL, NULL),
	(442, 'Incline Hammer Curl', 'Pull', 'Dumbbell', '{Biceps,Forearms}', '{}', NULL, NULL),
	(443, 'Lying Dumbbell Tricep Extension', 'Push', 'Dumbbell', '{Triceps}', '{"Front Delts"}', NULL, NULL),
	(444, 'One Arm Dumbbell Preacher Curl', 'Pull', 'Dumbbell', '{Biceps}', '{Forearms}', NULL, NULL),
	(445, 'Renegade Row', 'Pull', 'Dumbbell', '{"Upper Back",Lats,Core}', '{Biceps,Forearms,"Front Delts"}', NULL, NULL),
	(446, 'Seated Dumbbell Curl', 'Pull', 'Dumbbell', '{Biceps}', '{Forearms}', NULL, NULL),
	(447, 'Seated Dumbbell Tricep Extension', 'Push', 'Dumbbell', '{Triceps}', '{"Front Delts"}', NULL, NULL),
	(448, 'Single Leg Dumbbell Deadlift', 'Legs', 'Dumbbell', '{Glutes,Hamstrings}', '{Core,"Lower Back",Abductors}', NULL, NULL),
	(449, 'Tate Press', 'Push', 'Dumbbell', '{Triceps}', '{Chest,"Front Delts"}', NULL, NULL),
	(450, 'Zottman Curl', 'Pull', 'Dumbbell', '{Forearms,Biceps}', '{}', NULL, NULL),
	(451, 'Belt Squat', 'Legs', 'Machine', '{Quads,Glutes}', '{Adductors,Core}', NULL, NULL),
	(452, 'Hip Abduction', 'Legs', 'Machine', '{Abductors,Glutes}', '{Core}', NULL, NULL),
	(453, 'Machine Back Extension', 'Legs', 'Machine', '{"Lower Back",Glutes}', '{Hamstrings}', NULL, NULL),
	(454, 'Machine Bicep Curl', 'Pull', 'Machine', '{Biceps}', '{Forearms}', NULL, NULL),
	(455, 'Machine Lateral Raise', 'Push', 'Machine', '{"Lateral Delts"}', '{Traps}', NULL, NULL),
	(456, 'Machine Reverse Fly', 'Pull', 'Machine', '{"Rear Delts",Rhomboids}', '{"Upper Back",Traps}', NULL, NULL),
	(457, 'Machine Row', 'Pull', 'Machine', '{"Upper Back",Lats,Rhomboids}', '{"Rear Delts",Biceps,Forearms}', NULL, NULL),
	(458, 'Machine Seated Crunch', 'Core', 'Machine', '{Core}', '{"Hip Flexors"}', NULL, NULL),
	(459, 'Machine Shrug', 'Pull', 'Machine', '{Traps}', '{Forearms,"Upper Back"}', NULL, NULL),
	(460, 'Machine Tricep Extension', 'Push', 'Machine', '{Triceps}', '{"Front Delts"}', NULL, NULL),
	(461, 'Seated Calf Raise', 'Legs', 'Machine', '{Calves}', '{}', NULL, NULL),
	(462, 'Seated Dip Machine', 'Push', 'Machine', '{Chest,Triceps}', '{"Front Delts","Lower Chest"}', NULL, NULL),
	(463, 'Single Leg Press', 'Legs', 'Machine', '{Quads,Glutes}', '{Adductors,Hamstrings}', NULL, NULL),
	(464, 'Single Leg Seated Calf Raise', 'Legs', 'Machine', '{Calves}', '{}', NULL, NULL),
	(465, 'Sled Press Calf Raise', 'Legs', 'Machine', '{Calves}', '{}', NULL, NULL),
	(466, 'Standing Leg Curl', 'Legs', 'Machine', '{Hamstrings}', '{Calves}', NULL, NULL),
	(467, 'Vertical Leg Press', 'Legs', 'Machine', '{Quads,Glutes}', '{Adductors,Hamstrings}', NULL, NULL);


--
-- Data for Name: exercise_prs; Type: TABLE DATA; Schema: public; Owner: postgres
--

