-- Allow cascade so the delete doesn't fail on FK references
ALTER TABLE workout_sets DROP CONSTRAINT workout_sets_exercise_id_fkey;
ALTER TABLE workout_sets ADD CONSTRAINT workout_sets_exercise_id_fkey
  FOREIGN KEY (exercise_id) REFERENCES exercises(id) ON DELETE CASCADE;

-- Delete all default exercises and replace with catalog
DELETE FROM exercises WHERE user_id IS NULL;

INSERT INTO exercises (name, equipment, category, primary_muscles, secondary_muscles) VALUES
  ('Barbell Calf Raise', 'Barbell', 'Legs', ARRAY['Calves'], ARRAY[]::text[]),
  ('Barbell Curl', 'Barbell', 'Pull', ARRAY['Biceps'], ARRAY['Forearms']),
  ('Barbell Front Raise', 'Barbell', 'Push', ARRAY['Front Delts'], ARRAY['Lateral Delts']),
  ('Barbell Glute Bridge', 'Barbell', 'Legs', ARRAY['Glutes', 'Hamstrings'], ARRAY['Core', 'Adductors']),
  ('Barbell Hack Squat', 'Barbell', 'Legs', ARRAY['Quads', 'Glutes'], ARRAY['Adductors', 'Hamstrings']),
  ('Barbell Lunge', 'Barbell', 'Legs', ARRAY['Quads', 'Glutes'], ARRAY['Hamstrings', 'Adductors', 'Core']),
  ('Barbell Power Shrug', 'Barbell', 'Legs', ARRAY['Traps'], ARRAY['Glutes', 'Quads', 'Calves']),
  ('Barbell Pullover', 'Barbell', 'Push', ARRAY['Lats', 'Chest'], ARRAY['Triceps']),
  ('Barbell Reverse Lunge', 'Barbell', 'Legs', ARRAY['Glutes', 'Quads'], ARRAY['Hamstrings', 'Adductors']),
  ('Barbell Shrug', 'Barbell', 'Pull', ARRAY['Traps'], ARRAY['Forearms', 'Upper Back']),
  ('Behind The Back Barbell Shrug', 'Barbell', 'Pull', ARRAY['Traps'], ARRAY['Forearms', 'Upper Back']),
  ('Behind The Back Deadlift', 'Barbell', 'Legs', ARRAY['Glutes', 'Hamstrings', 'Lower Back'], ARRAY['Quads', 'Traps', 'Forearms']),
  ('Behind The Neck Press', 'Barbell', 'Core', ARRAY['Front Delts', 'Triceps', 'Lateral Delts'], ARRAY['Upper Back', 'Core']),
  ('Bench Pin Press', 'Barbell', 'Push', ARRAY['Chest', 'Triceps', 'Front Delts'], ARRAY['Upper Back', 'Lats']),
  ('Bench Press', 'Barbell', 'Push', ARRAY['Chest', 'Triceps', 'Front Delts'], ARRAY['Upper Back', 'Lats']),
  ('Bench Pull', 'Barbell', 'Pull', ARRAY['Upper Back', 'Lats', 'Rhomboids'], ARRAY['Rear Delts', 'Biceps', 'Forearms']),
  ('Bent Arm Barbell Pullover', 'Barbell', 'Push', ARRAY['Chest', 'Lats'], ARRAY['Triceps', 'Upper Chest']),
  ('Bent Over Row', 'Barbell', 'Pull', ARRAY['Upper Back', 'Lats', 'Rhomboids'], ARRAY['Rear Delts', 'Biceps', 'Forearms']),
  ('Box Squat', 'Barbell', 'Legs', ARRAY['Glutes', 'Quads'], ARRAY['Hamstrings', 'Adductors', 'Core']),
  ('Bulgarian Split Squat', 'Barbell', 'Legs', ARRAY['Quads', 'Glutes'], ARRAY['Adductors', 'Hamstrings', 'Core']),
  ('Cheat Curl', 'Barbell', 'Pull', ARRAY['Biceps', 'Forearms'], ARRAY['Upper Back']),
  ('Chest Press', 'Machine', 'Push', ARRAY['Chest', 'Triceps', 'Front Delts'], ARRAY['Upper Chest']),
  ('Chin Ups', 'Bodyweight', 'Pull', ARRAY['Lats', 'Biceps'], ARRAY['Upper Back', 'Forearms', 'Rhomboids']),
  ('Clean', 'Barbell', 'Legs', ARRAY['Quads', 'Glutes', 'Traps'], ARRAY['Hamstrings', 'Upper Back', 'Calves']),
  ('Clean and Jerk', 'Barbell', 'Legs', ARRAY['Quads', 'Glutes', 'Front Delts', 'Triceps'], ARRAY['Traps', 'Core', 'Upper Back']),
  ('Clean and Press', 'Barbell', 'Legs', ARRAY['Quads', 'Glutes', 'Front Delts', 'Triceps'], ARRAY['Traps', 'Core', 'Upper Back']),
  ('Clean High Pull', 'Barbell', 'Legs', ARRAY['Traps', 'Glutes', 'Quads'], ARRAY['Hamstrings', 'Upper Back', 'Calves']),
  ('Clean Pull', 'Barbell', 'Legs', ARRAY['Glutes', 'Hamstrings', 'Traps'], ARRAY['Quads', 'Upper Back', 'Calves']),
  ('Close Grip Bench Press', 'Barbell', 'Push', ARRAY['Triceps', 'Chest'], ARRAY['Front Delts', 'Upper Chest']),
  ('Close Grip Incline Bench Press', 'Barbell', 'Push', ARRAY['Upper Chest', 'Triceps'], ARRAY['Chest', 'Front Delts']),
  ('Deadlift', 'Barbell', 'Legs', ARRAY['Glutes', 'Hamstrings', 'Lower Back'], ARRAY['Quads', 'Traps', 'Upper Back', 'Forearms']),
  ('Decline Bench Press', 'Barbell', 'Push', ARRAY['Lower Chest', 'Chest', 'Triceps'], ARRAY['Front Delts']),
  ('Deficit Deadlift', 'Barbell', 'Legs', ARRAY['Glutes', 'Hamstrings', 'Lower Back'], ARRAY['Quads', 'Traps', 'Upper Back', 'Forearms']),
  ('Dips', 'Bodyweight', 'Push', ARRAY['Lower Chest', 'Triceps'], ARRAY['Chest', 'Front Delts']),
  ('Dumbbell Bench Press', 'Dumbbell', 'Push', ARRAY['Chest', 'Triceps', 'Front Delts'], ARRAY['Upper Back', 'Lats']),
  ('Dumbbell Bulgarian Split Squat', 'Dumbbell', 'Legs', ARRAY['Quads', 'Glutes'], ARRAY['Adductors', 'Hamstrings', 'Core']),
  ('Dumbbell Curl', 'Dumbbell', 'Pull', ARRAY['Biceps'], ARRAY['Forearms']),
  ('Dumbbell Fly', 'Dumbbell', 'Push', ARRAY['Chest'], ARRAY['Front Delts']),
  ('Dumbbell Lateral Raise', 'Dumbbell', 'Push', ARRAY['Lateral Delts'], ARRAY['Traps']),
  ('Dumbbell Row', 'Dumbbell', 'Pull', ARRAY['Upper Back', 'Lats', 'Rhomboids'], ARRAY['Rear Delts', 'Biceps', 'Forearms']),
  ('Dumbbell Shoulder Press', 'Dumbbell', 'Push', ARRAY['Front Delts', 'Triceps', 'Lateral Delts'], ARRAY['Upper Chest']),
  ('Dumbbell Shrug', 'Dumbbell', 'Pull', ARRAY['Traps'], ARRAY['Forearms', 'Upper Back']),
  ('EZ Bar Curl', 'EZ Bar', 'Pull', ARRAY['Biceps'], ARRAY['Forearms']),
  ('Floor Press', 'Barbell', 'Push', ARRAY['Chest', 'Triceps', 'Front Delts'], ARRAY['Upper Back', 'Lats']),
  ('Front Squat', 'Barbell', 'Legs', ARRAY['Quads', 'Glutes'], ARRAY['Core', 'Upper Back', 'Adductors']),
  ('Goblet Squat', 'Dumbbell', 'Legs', ARRAY['Quads', 'Glutes'], ARRAY['Core', 'Adductors']),
  ('Good Morning', 'Barbell', 'Legs', ARRAY['Hamstrings', 'Glutes', 'Lower Back'], ARRAY['Core']),
  ('Hack Squat', 'Machine', 'Legs', ARRAY['Quads', 'Glutes'], ARRAY['Adductors', 'Hamstrings']),
  ('Half Squat', 'Barbell', 'Legs', ARRAY['Quads', 'Glutes'], ARRAY['Adductors', 'Core']),
  ('Hammer Curl', 'Dumbbell', 'Pull', ARRAY['Biceps', 'Forearms'], ARRAY[]::text[]),
  ('Hang Clean', 'Barbell', 'Legs', ARRAY['Quads', 'Glutes', 'Traps'], ARRAY['Hamstrings', 'Upper Back', 'Calves']),
  ('Hang Power Clean', 'Barbell', 'Legs', ARRAY['Quads', 'Glutes', 'Traps'], ARRAY['Hamstrings', 'Upper Back', 'Calves']),
  ('Hang Snatch', 'Barbell', 'Legs', ARRAY['Glutes', 'Traps', 'Front Delts'], ARRAY['Quads', 'Upper Back', 'Core']),
  ('Hex Bar Deadlift', 'Barbell', 'Legs', ARRAY['Quads', 'Glutes', 'Hamstrings'], ARRAY['Lower Back', 'Traps', 'Forearms']),
  ('Hex Bar Shrug', 'Barbell', 'Pull', ARRAY['Traps'], ARRAY['Forearms', 'Upper Back']),
  ('Hip Adduction', 'Machine', 'Legs', ARRAY['Adductors'], ARRAY['Glutes']),
  ('Hip Thrust', 'Barbell', 'Legs', ARRAY['Glutes', 'Hamstrings'], ARRAY['Core', 'Adductors']),
  ('Horizontal Leg Press', 'Machine', 'Legs', ARRAY['Quads', 'Glutes'], ARRAY['Adductors', 'Hamstrings']),
  ('Incline Bench Press', 'Barbell', 'Push', ARRAY['Upper Chest', 'Chest', 'Front Delts'], ARRAY['Triceps']),
  ('Incline Dumbbell Bench Press', 'Dumbbell', 'Push', ARRAY['Upper Chest', 'Chest', 'Front Delts'], ARRAY['Triceps']),
  ('Jefferson Deadlift', 'Barbell', 'Legs', ARRAY['Quads', 'Glutes', 'Hamstrings'], ARRAY['Lower Back', 'Adductors', 'Forearms']),
  ('Jefferson Squat', 'Barbell', 'Legs', ARRAY['Quads', 'Glutes'], ARRAY['Adductors', 'Core', 'Hamstrings']),
  ('JM Press', 'Barbell', 'Push', ARRAY['Triceps'], ARRAY['Chest', 'Front Delts']),
  ('Landmine Press', 'Barbell', 'Push', ARRAY['Front Delts', 'Upper Chest', 'Triceps'], ARRAY['Core', 'Lateral Delts']),
  ('Landmine Squat', 'Barbell', 'Legs', ARRAY['Quads', 'Glutes'], ARRAY['Core', 'Adductors']),
  ('Lat Pulldown', 'Cable', 'Pull', ARRAY['Lats', 'Upper Back'], ARRAY['Biceps', 'Forearms', 'Rhomboids']),
  ('Leg Extension', 'Machine', 'Legs', ARRAY['Quads'], ARRAY['Hip Flexors']),
  ('Log Press', 'Barbell', 'Push', ARRAY['Front Delts', 'Triceps', 'Upper Chest'], ARRAY['Core', 'Lateral Delts']),
  ('Lying Leg Curl', 'Machine', 'Legs', ARRAY['Hamstrings'], ARRAY['Calves']),
  ('Lying Tricep Extension', 'Barbell', 'Push', ARRAY['Triceps'], ARRAY['Front Delts']),
  ('Machine Calf Raise', 'Machine', 'Legs', ARRAY['Calves'], ARRAY[]::text[]),
  ('Machine Chest Fly', 'Machine', 'Push', ARRAY['Chest'], ARRAY['Front Delts']),
  ('Machine Shoulder Press', 'Machine', 'Push', ARRAY['Front Delts', 'Triceps', 'Lateral Delts'], ARRAY['Upper Chest']),
  ('Meadows Row', 'Barbell', 'Pull', ARRAY['Lats', 'Upper Back', 'Rhomboids'], ARRAY['Biceps', 'Rear Delts', 'Forearms']),
  ('Military Press', 'Barbell', 'Push', ARRAY['Front Delts', 'Triceps'], ARRAY['Lateral Delts', 'Upper Chest', 'Core']),
  ('Muscle Snatch', 'Barbell', 'Pull', ARRAY['Front Delts', 'Traps', 'Upper Back'], ARRAY['Glutes', 'Core']),
  ('Muscle Ups', 'Bodyweight', 'Push', ARRAY['Lats', 'Chest', 'Triceps'], ARRAY['Upper Back', 'Biceps', 'Front Delts', 'Core']),
  ('Neck Curl', 'Machine', 'Core', ARRAY['Neck'], ARRAY[]::text[]),
  ('Neck Extension', 'Machine', 'Core', ARRAY['Neck'], ARRAY[]::text[]),
  ('One Arm Landmine Press', 'Barbell', 'Push', ARRAY['Front Delts', 'Upper Chest', 'Triceps'], ARRAY['Core', 'Lateral Delts']),
  ('Overhead Squat', 'Barbell', 'Legs', ARRAY['Quads', 'Glutes', 'Front Delts', 'Upper Back'], ARRAY['Core', 'Hamstrings']),
  ('Pause Deadlift', 'Barbell', 'Legs', ARRAY['Glutes', 'Hamstrings', 'Lower Back'], ARRAY['Quads', 'Traps', 'Upper Back', 'Forearms']),
  ('Pause Squat', 'Barbell', 'Legs', ARRAY['Quads', 'Glutes'], ARRAY['Adductors', 'Core', 'Hamstrings']),
  ('Paused Bench Press', 'Barbell', 'Push', ARRAY['Chest', 'Triceps', 'Front Delts'], ARRAY['Upper Back', 'Lats']),
  ('Pendlay Row', 'Barbell', 'Pull', ARRAY['Upper Back', 'Lats', 'Rhomboids'], ARRAY['Rear Delts', 'Biceps', 'Forearms']),
  ('Pin Squat', 'Barbell', 'Legs', ARRAY['Quads', 'Glutes'], ARRAY['Adductors', 'Core', 'Hamstrings']),
  ('Power Clean', 'Barbell', 'Legs', ARRAY['Quads', 'Glutes', 'Traps'], ARRAY['Hamstrings', 'Upper Back', 'Calves']),
  ('Power Snatch', 'Barbell', 'Legs', ARRAY['Glutes', 'Traps', 'Front Delts'], ARRAY['Quads', 'Upper Back', 'Core']),
  ('Preacher Curl', 'Barbell', 'Pull', ARRAY['Biceps'], ARRAY['Forearms']),
  ('Pull Ups', 'Bodyweight', 'Pull', ARRAY['Lats', 'Upper Back'], ARRAY['Biceps', 'Forearms', 'Rhomboids']),
  ('Push Jerk', 'Barbell', 'Legs', ARRAY['Front Delts', 'Triceps', 'Quads', 'Glutes'], ARRAY['Core', 'Upper Back']),
  ('Push Press', 'Barbell', 'Legs', ARRAY['Front Delts', 'Triceps', 'Quads', 'Glutes'], ARRAY['Core', 'Upper Back']),
  ('Push Ups', 'Bodyweight', 'Push', ARRAY['Chest', 'Triceps', 'Front Delts'], ARRAY['Core']),
  ('Rack Pull', 'Barbell', 'Legs', ARRAY['Glutes', 'Hamstrings', 'Lower Back'], ARRAY['Traps', 'Upper Back', 'Forearms']),
  ('Reverse Barbell Curl', 'Barbell', 'Pull', ARRAY['Forearms', 'Biceps'], ARRAY[]::text[]),
  ('Reverse Grip Bench Press', 'Barbell', 'Push', ARRAY['Upper Chest', 'Triceps'], ARRAY['Chest', 'Front Delts']),
  ('Reverse Wrist Curl', 'Barbell', 'Pull', ARRAY['Forearms'], ARRAY[]::text[]),
  ('Romanian Deadlift', 'Barbell', 'Legs', ARRAY['Hamstrings', 'Glutes'], ARRAY['Lower Back', 'Adductors']),
  ('Safety Bar Squat', 'Barbell', 'Legs', ARRAY['Quads', 'Glutes'], ARRAY['Upper Back', 'Core', 'Adductors']),
  ('Seated Cable Row', 'Cable', 'Pull', ARRAY['Upper Back', 'Lats', 'Rhomboids'], ARRAY['Rear Delts', 'Biceps', 'Forearms']),
  ('Seated Dumbbell Shoulder Press', 'Dumbbell', 'Push', ARRAY['Front Delts', 'Triceps', 'Lateral Delts'], ARRAY['Upper Chest']),
  ('Seated Leg Curl', 'Machine', 'Legs', ARRAY['Hamstrings'], ARRAY['Calves']),
  ('Seated Shoulder Press', 'Barbell', 'Push', ARRAY['Front Delts', 'Triceps'], ARRAY['Lateral Delts', 'Upper Chest', 'Core']),
  ('Shoulder Pin Press', 'Barbell', 'Push', ARRAY['Front Delts', 'Triceps'], ARRAY['Lateral Delts', 'Upper Chest', 'Core']),
  ('Shoulder Press', 'Barbell', 'Push', ARRAY['Front Delts', 'Triceps'], ARRAY['Lateral Delts', 'Upper Chest', 'Core']),
  ('Single Leg Deadlift', 'Barbell', 'Legs', ARRAY['Glutes', 'Hamstrings'], ARRAY['Core', 'Lower Back', 'Abductors']),
  ('Single Leg Romanian Deadlift', 'Barbell', 'Legs', ARRAY['Glutes', 'Hamstrings'], ARRAY['Core', 'Lower Back', 'Abductors']),
  ('Sled Leg Press', 'Machine', 'Legs', ARRAY['Quads', 'Glutes'], ARRAY['Adductors', 'Hamstrings']),
  ('Smith Machine Bench Press', 'Machine', 'Push', ARRAY['Chest', 'Triceps', 'Front Delts'], ARRAY['Upper Back', 'Lats']),
  ('Smith Machine Shrug', 'Machine', 'Pull', ARRAY['Traps'], ARRAY['Forearms', 'Upper Back']),
  ('Smith Machine Squat', 'Machine', 'Legs', ARRAY['Quads', 'Glutes'], ARRAY['Adductors', 'Core', 'Hamstrings']),
  ('Snatch', 'Barbell', 'Legs', ARRAY['Glutes', 'Traps', 'Front Delts'], ARRAY['Quads', 'Upper Back', 'Core']),
  ('Snatch Deadlift', 'Barbell', 'Legs', ARRAY['Glutes', 'Hamstrings', 'Lower Back'], ARRAY['Quads', 'Traps', 'Upper Back', 'Forearms']),
  ('Snatch Pull', 'Barbell', 'Legs', ARRAY['Glutes', 'Hamstrings', 'Traps'], ARRAY['Quads', 'Upper Back', 'Calves']),
  ('Spider Curl', 'Barbell', 'Pull', ARRAY['Biceps'], ARRAY['Forearms']),
  ('Split Jerk', 'Barbell', 'Legs', ARRAY['Front Delts', 'Triceps', 'Quads', 'Glutes'], ARRAY['Core', 'Upper Back']),
  ('Split Squat', 'Barbell', 'Legs', ARRAY['Quads', 'Glutes'], ARRAY['Adductors', 'Hamstrings', 'Core']),
  ('Spoto Press', 'Barbell', 'Push', ARRAY['Chest', 'Triceps', 'Front Delts'], ARRAY['Upper Back', 'Lats']),
  ('Squat', 'Barbell', 'Legs', ARRAY['Quads', 'Glutes'], ARRAY['Adductors', 'Core', 'Hamstrings']),
  ('Stiff Leg Deadlift', 'Barbell', 'Legs', ARRAY['Hamstrings', 'Glutes', 'Lower Back'], ARRAY['Adductors']),
  ('Strict Curl', 'Barbell', 'Pull', ARRAY['Biceps'], ARRAY['Forearms']),
  ('Sumo Deadlift', 'Barbell', 'Legs', ARRAY['Glutes', 'Hamstrings', 'Adductors'], ARRAY['Quads', 'Lower Back', 'Traps', 'Forearms']),
  ('Sumo Squat', 'Barbell', 'Legs', ARRAY['Quads', 'Glutes', 'Adductors'], ARRAY['Hamstrings', 'Core']),
  ('T Bar Row', 'Barbell', 'Pull', ARRAY['Upper Back', 'Lats', 'Rhomboids'], ARRAY['Rear Delts', 'Biceps', 'Forearms']),
  ('Thruster', 'Barbell', 'Push', ARRAY['Quads', 'Glutes', 'Front Delts', 'Triceps'], ARRAY['Core', 'Upper Chest']),
  ('Tricep Extension', 'Barbell', 'Push', ARRAY['Triceps'], ARRAY['Front Delts']),
  ('Tricep Pushdown', 'Cable', 'Push', ARRAY['Triceps'], ARRAY['Forearms']),
  ('Upright Row', 'Barbell', 'Pull', ARRAY['Lateral Delts', 'Traps'], ARRAY['Front Delts', 'Upper Back']),
  ('Viking Press', 'Barbell', 'Push', ARRAY['Front Delts', 'Triceps', 'Upper Chest'], ARRAY['Core', 'Lateral Delts']),
  ('Walking Lunge', 'Barbell', 'Legs', ARRAY['Quads', 'Glutes'], ARRAY['Hamstrings', 'Adductors', 'Core']),
  ('Wall Ball', 'Dumbbell', 'Legs', ARRAY['Quads', 'Glutes', 'Front Delts'], ARRAY['Core', 'Triceps']),
  ('Wide Grip Bench Press', 'Barbell', 'Push', ARRAY['Chest', 'Triceps', 'Front Delts'], ARRAY['Upper Back', 'Lats']),
  ('Wrist Curl', 'Barbell', 'Pull', ARRAY['Forearms'], ARRAY[]::text[]),
  ('Yates Row', 'Barbell', 'Pull', ARRAY['Lats', 'Upper Back', 'Rhomboids'], ARRAY['Biceps', 'Rear Delts', 'Forearms']),
  ('Z Press', 'Barbell', 'Push', ARRAY['Front Delts', 'Triceps', 'Core'], ARRAY['Upper Back', 'Lateral Delts']),
  ('Zercher Deadlift', 'Barbell', 'Legs', ARRAY['Quads', 'Glutes', 'Hamstrings'], ARRAY['Lower Back', 'Traps', 'Forearms', 'Core']),
  ('Zercher Squat', 'Barbell', 'Legs', ARRAY['Quads', 'Glutes'], ARRAY['Core', 'Upper Back', 'Adductors']),
  ('Cable Bicep Curl', 'Cable', 'Pull', ARRAY['Biceps'], ARRAY['Forearms']),
  ('Cable Crunch', 'Cable', 'Core', ARRAY['Core'], ARRAY['Hip Flexors']),
  ('Cable External Rotation', 'Cable', 'Pull', ARRAY['Rear Delts'], ARRAY['Upper Back']),
  ('Cable Fly', 'Cable', 'Push', ARRAY['Chest'], ARRAY['Front Delts']),
  ('Cable Hammer Curl', 'Cable', 'Pull', ARRAY['Biceps', 'Forearms'], ARRAY[]::text[]),
  ('Cable Kickback', 'Cable', 'Push', ARRAY['Triceps'], ARRAY['Rear Delts']),
  ('Cable Lateral Raise', 'Cable', 'Push', ARRAY['Lateral Delts'], ARRAY['Traps']),
  ('Cable Leg Extension', 'Cable', 'Legs', ARRAY['Quads'], ARRAY['Hip Flexors']),
  ('Cable Overhead Tricep Extension', 'Cable', 'Push', ARRAY['Triceps'], ARRAY['Front Delts']),
  ('Cable Pull Through', 'Cable', 'Legs', ARRAY['Glutes', 'Hamstrings'], ARRAY['Lower Back', 'Adductors']),
  ('Cable Reverse Fly', 'Cable', 'Pull', ARRAY['Rear Delts', 'Rhomboids'], ARRAY['Upper Back', 'Traps']),
  ('Cable Shrug', 'Cable', 'Pull', ARRAY['Traps'], ARRAY['Forearms', 'Upper Back']),
  ('Cable Upright Row', 'Cable', 'Pull', ARRAY['Lateral Delts', 'Traps'], ARRAY['Front Delts', 'Upper Back']),
  ('Cable Woodchopper', 'Cable', 'Core', ARRAY['Obliques', 'Core'], ARRAY['Hip Flexors']),
  ('Close Grip Lat Pulldown', 'Cable', 'Pull', ARRAY['Lats', 'Upper Back'], ARRAY['Biceps', 'Forearms', 'Rhomboids']),
  ('Face Pull', 'Cable', 'Pull', ARRAY['Rear Delts', 'Upper Back', 'Rhomboids'], ARRAY['Traps']),
  ('High Pulley Crunch', 'Cable', 'Core', ARRAY['Core'], ARRAY['Hip Flexors']),
  ('Incline Cable Curl', 'Cable', 'Pull', ARRAY['Biceps'], ARRAY['Forearms']),
  ('Lying Cable Curl', 'Cable', 'Legs', ARRAY['Hamstrings'], ARRAY['Calves']),
  ('One Arm Cable Bicep Curl', 'Cable', 'Pull', ARRAY['Biceps'], ARRAY['Forearms']),
  ('One Arm Lat Pulldown', 'Cable', 'Pull', ARRAY['Lats', 'Upper Back'], ARRAY['Biceps', 'Forearms', 'Rhomboids']),
  ('One Arm Pulldown', 'Cable', 'Pull', ARRAY['Lats'], ARRAY['Upper Back', 'Triceps']),
  ('One Arm Seated Cable Row', 'Cable', 'Pull', ARRAY['Upper Back', 'Lats', 'Rhomboids'], ARRAY['Rear Delts', 'Biceps', 'Forearms']),
  ('Overhead Cable Curl', 'Cable', 'Pull', ARRAY['Biceps'], ARRAY['Forearms']),
  ('Reverse Grip Lat Pulldown', 'Cable', 'Pull', ARRAY['Lats', 'Biceps'], ARRAY['Upper Back', 'Forearms', 'Rhomboids']),
  ('Reverse Grip Tricep Pushdown', 'Cable', 'Push', ARRAY['Triceps'], ARRAY['Forearms']),
  ('Standing Cable Crunch', 'Cable', 'Core', ARRAY['Core'], ARRAY['Hip Flexors']),
  ('Straight Arm Pulldown', 'Cable', 'Pull', ARRAY['Lats'], ARRAY['Upper Back', 'Triceps']),
  ('Tricep Rope Pushdown', 'Cable', 'Push', ARRAY['Triceps'], ARRAY['Forearms']),
  ('Arnold Press', 'Dumbbell', 'Push', ARRAY['Front Delts', 'Lateral Delts', 'Triceps'], ARRAY['Upper Chest']),
  ('Bent Over Dumbbell Row', 'Dumbbell', 'Pull', ARRAY['Upper Back', 'Lats', 'Rhomboids'], ARRAY['Rear Delts', 'Biceps', 'Forearms']),
  ('Chest Supported Dumbbell Row', 'Dumbbell', 'Pull', ARRAY['Upper Back', 'Lats', 'Rhomboids'], ARRAY['Rear Delts', 'Biceps', 'Forearms']),
  ('Close Grip Dumbbell Bench Press', 'Dumbbell', 'Push', ARRAY['Triceps', 'Chest'], ARRAY['Front Delts', 'Upper Chest']),
  ('Decline Dumbbell Bench Press', 'Dumbbell', 'Push', ARRAY['Lower Chest', 'Chest', 'Triceps'], ARRAY['Front Delts']),
  ('Decline Dumbbell Fly', 'Dumbbell', 'Push', ARRAY['Lower Chest', 'Chest'], ARRAY['Front Delts']),
  ('Dumbbell Bench Pull', 'Dumbbell', 'Pull', ARRAY['Upper Back', 'Lats', 'Rhomboids'], ARRAY['Rear Delts', 'Biceps', 'Forearms']),
  ('Dumbbell Calf Raise', 'Dumbbell', 'Legs', ARRAY['Calves'], ARRAY[]::text[]),
  ('Dumbbell Clean and Press', 'Dumbbell', 'Legs', ARRAY['Quads', 'Glutes', 'Front Delts', 'Triceps'], ARRAY['Traps', 'Core', 'Upper Back']),
  ('Dumbbell Concentration Curl', 'Dumbbell', 'Pull', ARRAY['Biceps'], ARRAY['Forearms']),
  ('Dumbbell Deadlift', 'Dumbbell', 'Legs', ARRAY['Glutes', 'Hamstrings', 'Lower Back'], ARRAY['Quads', 'Traps', 'Upper Back', 'Forearms']),
  ('Dumbbell External Rotation', 'Dumbbell', 'Pull', ARRAY['Rear Delts'], ARRAY['Upper Back']),
  ('Dumbbell Face Pull', 'Dumbbell', 'Pull', ARRAY['Rear Delts', 'Upper Back', 'Rhomboids'], ARRAY['Traps']),
  ('Dumbbell Floor Press', 'Dumbbell', 'Push', ARRAY['Chest', 'Triceps', 'Front Delts'], ARRAY['Upper Back', 'Lats']),
  ('Dumbbell Front Raise', 'Dumbbell', 'Push', ARRAY['Front Delts'], ARRAY['Lateral Delts']),
  ('Dumbbell Front Squat', 'Dumbbell', 'Legs', ARRAY['Quads', 'Glutes'], ARRAY['Core', 'Upper Back', 'Adductors']),
  ('Dumbbell Hang Clean', 'Dumbbell', 'Legs', ARRAY['Quads', 'Glutes', 'Traps'], ARRAY['Hamstrings', 'Upper Back', 'Calves']),
  ('Dumbbell High Pull', 'Dumbbell', 'Legs', ARRAY['Traps', 'Glutes', 'Quads'], ARRAY['Hamstrings', 'Upper Back', 'Calves']),
  ('Dumbbell Incline Y Raise', 'Dumbbell', 'Pull', ARRAY['Rear Delts', 'Upper Back'], ARRAY['Traps', 'Rhomboids']),
  ('Dumbbell Lunge', 'Dumbbell', 'Legs', ARRAY['Quads', 'Glutes'], ARRAY['Hamstrings', 'Adductors', 'Core']),
  ('Dumbbell Pullover', 'Dumbbell', 'Push', ARRAY['Lats', 'Chest'], ARRAY['Triceps']),
  ('Dumbbell Push Press', 'Dumbbell', 'Legs', ARRAY['Front Delts', 'Triceps', 'Quads', 'Glutes'], ARRAY['Core', 'Upper Back']),
  ('Dumbbell Reverse Curl', 'Dumbbell', 'Pull', ARRAY['Forearms', 'Biceps'], ARRAY[]::text[]),
  ('Dumbbell Reverse Fly', 'Dumbbell', 'Pull', ARRAY['Rear Delts', 'Rhomboids'], ARRAY['Upper Back', 'Traps']),
  ('Dumbbell Reverse Wrist Curl', 'Dumbbell', 'Pull', ARRAY['Forearms'], ARRAY[]::text[]),
  ('Dumbbell Romanian Deadlift', 'Dumbbell', 'Legs', ARRAY['Hamstrings', 'Glutes'], ARRAY['Lower Back', 'Adductors']),
  ('Dumbbell Side Bend', 'Dumbbell', 'Core', ARRAY['Obliques'], ARRAY['Core']),
  ('Dumbbell Snatch', 'Dumbbell', 'Legs', ARRAY['Glutes', 'Traps', 'Front Delts'], ARRAY['Quads', 'Upper Back', 'Core']),
  ('Dumbbell Split Squat', 'Dumbbell', 'Legs', ARRAY['Quads', 'Glutes'], ARRAY['Adductors', 'Hamstrings', 'Core']),
  ('Dumbbell Squat', 'Dumbbell', 'Legs', ARRAY['Quads', 'Glutes'], ARRAY['Adductors', 'Core', 'Hamstrings']),
  ('Dumbbell Thruster', 'Dumbbell', 'Push', ARRAY['Quads', 'Glutes', 'Front Delts', 'Triceps'], ARRAY['Core', 'Upper Chest']),
  ('Dumbbell Tricep Extension', 'Dumbbell', 'Push', ARRAY['Triceps'], ARRAY['Front Delts']),
  ('Dumbbell Tricep Kickback', 'Dumbbell', 'Push', ARRAY['Triceps'], ARRAY['Rear Delts']),
  ('Dumbbell Upright Row', 'Dumbbell', 'Pull', ARRAY['Lateral Delts', 'Traps'], ARRAY['Front Delts', 'Upper Back']),
  ('Dumbbell Walking Calf Raise', 'Dumbbell', 'Legs', ARRAY['Calves'], ARRAY[]::text[]),
  ('Dumbbell Wrist Curl', 'Dumbbell', 'Pull', ARRAY['Forearms'], ARRAY[]::text[]),
  ('Dumbbell Z Press', 'Dumbbell', 'Push', ARRAY['Front Delts', 'Triceps', 'Core'], ARRAY['Upper Back', 'Lateral Delts']),
  ('Incline Dumbbell Curl', 'Dumbbell', 'Pull', ARRAY['Biceps'], ARRAY['Forearms']),
  ('Incline Dumbbell Fly', 'Dumbbell', 'Push', ARRAY['Upper Chest', 'Chest'], ARRAY['Front Delts']),
  ('Incline Hammer Curl', 'Dumbbell', 'Pull', ARRAY['Biceps', 'Forearms'], ARRAY[]::text[]),
  ('Lying Dumbbell Tricep Extension', 'Dumbbell', 'Push', ARRAY['Triceps'], ARRAY['Front Delts']),
  ('One Arm Dumbbell Preacher Curl', 'Dumbbell', 'Pull', ARRAY['Biceps'], ARRAY['Forearms']),
  ('Renegade Row', 'Dumbbell', 'Pull', ARRAY['Upper Back', 'Lats', 'Core'], ARRAY['Biceps', 'Forearms', 'Front Delts']),
  ('Seated Dumbbell Curl', 'Dumbbell', 'Pull', ARRAY['Biceps'], ARRAY['Forearms']),
  ('Seated Dumbbell Tricep Extension', 'Dumbbell', 'Push', ARRAY['Triceps'], ARRAY['Front Delts']),
  ('Single Leg Dumbbell Deadlift', 'Dumbbell', 'Legs', ARRAY['Glutes', 'Hamstrings'], ARRAY['Core', 'Lower Back', 'Abductors']),
  ('Tate Press', 'Dumbbell', 'Push', ARRAY['Triceps'], ARRAY['Chest', 'Front Delts']),
  ('Zottman Curl', 'Dumbbell', 'Pull', ARRAY['Forearms', 'Biceps'], ARRAY[]::text[]),
  ('Belt Squat', 'Machine', 'Legs', ARRAY['Quads', 'Glutes'], ARRAY['Adductors', 'Core']),
  ('Hip Abduction', 'Machine', 'Legs', ARRAY['Abductors', 'Glutes'], ARRAY['Core']),
  ('Machine Back Extension', 'Machine', 'Legs', ARRAY['Lower Back', 'Glutes'], ARRAY['Hamstrings']),
  ('Machine Bicep Curl', 'Machine', 'Pull', ARRAY['Biceps'], ARRAY['Forearms']),
  ('Machine Lateral Raise', 'Machine', 'Push', ARRAY['Lateral Delts'], ARRAY['Traps']),
  ('Machine Reverse Fly', 'Machine', 'Pull', ARRAY['Rear Delts', 'Rhomboids'], ARRAY['Upper Back', 'Traps']),
  ('Machine Row', 'Machine', 'Pull', ARRAY['Upper Back', 'Lats', 'Rhomboids'], ARRAY['Rear Delts', 'Biceps', 'Forearms']),
  ('Machine Seated Crunch', 'Machine', 'Core', ARRAY['Core'], ARRAY['Hip Flexors']),
  ('Machine Shrug', 'Machine', 'Pull', ARRAY['Traps'], ARRAY['Forearms', 'Upper Back']),
  ('Machine Tricep Extension', 'Machine', 'Push', ARRAY['Triceps'], ARRAY['Front Delts']),
  ('Seated Calf Raise', 'Machine', 'Legs', ARRAY['Calves'], ARRAY[]::text[]),
  ('Seated Dip Machine', 'Machine', 'Push', ARRAY['Chest', 'Triceps'], ARRAY['Front Delts', 'Lower Chest']),
  ('Single Leg Press', 'Machine', 'Legs', ARRAY['Quads', 'Glutes'], ARRAY['Adductors', 'Hamstrings']),
  ('Single Leg Seated Calf Raise', 'Machine', 'Legs', ARRAY['Calves'], ARRAY[]::text[]),
  ('Sled Press Calf Raise', 'Machine', 'Legs', ARRAY['Calves'], ARRAY[]::text[]),
  ('Standing Leg Curl', 'Machine', 'Legs', ARRAY['Hamstrings'], ARRAY['Calves']),
  ('Vertical Leg Press', 'Machine', 'Legs', ARRAY['Quads', 'Glutes'], ARRAY['Adductors', 'Hamstrings']);
